// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkrjGr1QbegkVLLNRrA-fe0n9t8egCFbo',
    appId: '1:70914324775:android:6e89c65dd3bc5020295102',
    messagingSenderId: '70914324775',
    projectId: 'hectaria-agdata-026',
    storageBucket: 'hectaria-agdata-026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXCQLk93LcaxptNRGjL8Usq6CnKXhWxzc',
    appId: '1:70914324775:ios:ab43af92da5653b3295102',
    messagingSenderId: '70914324775',
    projectId: 'hectaria-agdata-026',
    storageBucket: 'hectaria-agdata-026.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuECguzBFzLfO8bAthpTp1u1eq5P7ybfU',
    appId: '1:70914324775:web:c78e85eb61fe0afd295102',
    messagingSenderId: '70914324775',
    projectId: 'hectaria-agdata-026',
    authDomain: 'hectaria-agdata-026.firebaseapp.com',
    storageBucket: 'hectaria-agdata-026.firebasestorage.app',
    measurementId: 'G-7VL3MT5MKG',
  );
}
