name: CD AGData (Entrega Continua)

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build_android:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup do Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: |
          cd mobile
          flutter pub get

      - name: Gerar APK de Release
        run: |
          cd mobile
          flutter build apk --release

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: agdata-app-release
          path: mobile/build/app/outputs/flutter-apk/app-release.apk