name: "Z - Gerador de APK"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  release:
    name: Compilar APK
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Deps
        run: |
          cd mobile
          flutter pub get

      - name: Build
        run: |
          cd mobile
          flutter build apk --release

      - name: Artefato
        uses: actions/upload-artifact@v4
        with:
          name: AGData-Release
          path: mobile/build/app/outputs/flutter-apk/app-release.apk